Feature/new user registration route
deremenko/hospital-project-backend pull request #4
Opened 2024-02-02 09:11 UTC by deremenko

2024-02-02 09:19 UTC, baklanovairina requested changes

2024-02-02 09:19 UTC, baklanovairina commented on app.js
> +    console.error
скобки где потерял и параметр?

2024-02-02 09:19 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +      const userData = await userService.registrationUser(login, password);
почему все сплошным текстом написано? Делай отступы логические

2024-02-02 09:19 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +      console.log(userData.refreshToken)
удали консоль

2024-02-02 09:19 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +      res.cookie('refreshToken', userData.refreshToken, {maxAge: 30 * 24 * 60 * 60});
где httpOnly?
maxAge: 30 * 24 * 60 * 60 - это вообще никто не должен считать, оставь рядом коммент, сколько здесь часов/дней

2024-02-02 09:19 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +      return res.json(userData);
return лишний
где статус?

2024-02-02 09:19 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +      console.log(err)
какая еще консоль? Ты как на фронт ошибку отправлять будешь?
делай эксепшены и мидлвар для обработки ошибки, консоль удаляй

2024-02-02 09:19 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +class userController {
классы называются по PascalCase

2024-02-02 09:19 UTC, baklanovairina commented on scr/router/index.js
> +router.get('/refresh', userController.refresh);
у тебя нет такого контроллера

2024-02-02 09:19 UTC, baklanovairina commented on scr/router/index.js
> +router.post('/registration', userController.registration);
где валидация??

2024-02-02 09:19 UTC, baklanovairina commented on scr/router/index.js
> +const userController = require('./../controllers/user-controller.js');
PascalCase

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/token-services.js
> +class tokenService {
PascalCase тк это класс

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/token-services.js
> +    if (!process.env.JWT_ACCESS_SECRET || !process.env.JWT_REFRESH_SECRET) {
это должно хранится в конфиге 
и с чего бы их там не будет? Это обязательные данные как порт, ты же не проверяешь если порт

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/token-services.js
> +    const accessToken = jwt.sign(payload, process.env.JWT_ACCESS_SECRET, {expiresIn: "30m"})
сплошняком снова все написал

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/token-services.js
> +    if (tokenData) {
тоже сплошной текст

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/token-services.js
> +module.exports = new tokenService();
PascalCase

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/user-services.js
> +class userService {
PascalCase

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/user-services.js
> +const tokenService = require("./token-services.js");
PascalCase

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/user-services.js
> +const userModel =  require("../models/user-model.js")
userModel - лишнее слово Model
и PascalCase

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/user-services.js
> +    const candidate = await userModel.findOne({login});
пробел { login }
+отступы

2024-02-02 09:19 UTC, baklanovairina commented on scr/services/user-services.js
> +      throw new Error(`Пользователь с логином ${login} уже существует`)
делай эксепшены и мидлвар для обработки ошибки

2024-02-02 10:50 UTC, deremenko commented on app.js
> +    console.error
Corrected

2024-02-02 10:55 UTC, deremenko commented on scr/controllers/user-controller.js
> +      const userData = await userService.registrationUser(login, password);
Corrected

2024-02-02 10:55 UTC, deremenko commented on scr/controllers/user-controller.js
> +      console.log(userData.refreshToken)
Corrected

2024-02-02 10:59 UTC, deremenko commented on scr/controllers/user-controller.js
> +      res.cookie('refreshToken', userData.refreshToken, {maxAge: 30 * 24 * 60 * 60});
Corrected

2024-02-02 11:17 UTC, deremenko commented on scr/controllers/user-controller.js
> +      return res.json(userData);
Corrected

2024-02-02 11:25 UTC, deremenko commented on scr/controllers/user-controller.js
> +      console.log(err)
Corrected

2024-02-02 11:43 UTC, deremenko commented on scr/controllers/user-controller.js
> +class userController {
Corrected

2024-02-02 11:43 UTC, deremenko commented on scr/router/index.js
> +router.get('/refresh', userController.refresh);
Corrected

2024-02-02 11:44 UTC, deremenko commented on scr/router/index.js
> +const userController = require('./../controllers/user-controller.js');
Corrected

2024-02-02 11:44 UTC, deremenko commented on scr/services/token-services.js
> +class tokenService {
Corrected

2024-02-02 11:46 UTC, deremenko commented on scr/services/token-services.js
> +    if (!process.env.JWT_ACCESS_SECRET || !process.env.JWT_REFRESH_SECRET) {
Я просто глупую ошибку искал и потому вообще каждый вариант прорабатывал. А потом убрать забыл...

2024-02-02 11:46 UTC, deremenko commented on scr/services/token-services.js
> +    const accessToken = jwt.sign(payload, process.env.JWT_ACCESS_SECRET, {expiresIn: "30m"})
Corrected

2024-02-02 11:46 UTC, deremenko commented on scr/services/token-services.js
> +    if (tokenData) {
Corrected

2024-02-02 11:47 UTC, deremenko commented on scr/services/token-services.js
> +module.exports = new tokenService();
Corrected

2024-02-02 11:47 UTC, deremenko commented on scr/services/user-services.js
> +class userService {
Corrected

2024-02-02 11:47 UTC, deremenko commented on scr/services/user-services.js
> +const tokenService = require("./token-services.js");
Corrected

2024-02-02 11:47 UTC, deremenko commented on scr/services/user-services.js
> +const userModel =  require("../models/user-model.js")
Corrected

2024-02-02 11:47 UTC, deremenko commented on scr/services/user-services.js
> +    const candidate = await userModel.findOne({login});
Corrected

2024-02-02 12:42 UTC, deremenko commented on scr/services/user-services.js
> +      throw new Error(`Пользователь с логином ${login} уже существует`)
Corrected

2024-02-02 12:43 UTC, deremenko commented on scr/router/index.js
> +router.post('/registration', userController.registration);
Corrected

2024-02-05 06:52 UTC, baklanovairina requested changes

2024-02-05 06:52 UTC, baklanovairina commented on app.js
> +const mongoose = require("mongoose");
порядок, сначала идут импорты библиотек, потом уже модулей

2024-02-05 06:52 UTC, baklanovairina commented on app.js
> +app.use(cors());
опция для корсов нужны, иначе я даже протестить не смогу

2024-02-05 06:52 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +const userService = require("../services/user-services.js");
это класс, они называются по PascalCase

2024-02-05 06:52 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +      const { login, password } = req.body;
отступ после этой строки

2024-02-05 06:52 UTC, baklanovairina commented on scr/controllers/user-controller.js
> +      res.cookie('refreshToken', userData.refreshToken, {maxAge: 30 * 24 * 60 * 60, httpOnly: true});
{maxAge: 30 * 24 * 60 * 60, httpOnly: true} 
вынеси объект в глобальную константу, он будет повторяться
можно прямо в этом файле

2024-02-05 06:52 UTC, baklanovairina commented on scr/middlewares/error-middleware.js
> +  console.error(err);
удали консоль

2024-02-05 06:52 UTC, baklanovairina commented on scr/middlewares/user-validation.js
> +    .notEmpty(),
подумай о порядке вызова методов

2024-02-05 06:52 UTC, baklanovairina commented on scr/middlewares/user-validation.js
> +const { validatorResult } = require('./validation-result');
отступ от импортов

2024-02-05 06:52 UTC, baklanovairina commented on scr/middlewares/user-validation.js
> +    .isString()
где трим?

2024-02-05 06:52 UTC, baklanovairina commented on scr/middlewares/user-validation.js
> +    .matches(/^(?=.*[A-Za-z])(?=.*\d).+$/),
вместо isLength можно длину указать в matches

2024-02-05 06:52 UTC, baklanovairina commented on scr/middlewares/user-validation.js
> +module.exports = {
отступ

2024-02-05 06:52 UTC, baklanovairina commented on scr/router/index.js
> +const userController = require('./../controllers/user-controller.js');
где блин Corrected, если не Corrected
я же сказала это PascalCase

2024-02-05 06:52 UTC, baklanovairina commented on scr/services/token-services.js
> +    const accessToken = jwt.sign(payload, process.env.JWT_ACCESS_SECRET, {expiresIn: "30m"})
process.env.JWT_ACCESS_SECRET
process.env.JWT_ACCESS_SECRET 
они должны быть в конфиге

2024-02-05 06:52 UTC, baklanovairina commented on scr/services/token-services.js
> +    if (tokenData) {
перед if отступ

2024-02-05 06:52 UTC, baklanovairina commented on scr/services/user-services.js
> +const tokenService = require("./token-services.js");
PascalCase

2024-02-05 06:52 UTC, baklanovairina commented on scr/services/user-services.js
> +      throw ApiError.BadRequest(`Пользователь с логином ${login} уже существует`)
перед блоком if отступ

2024-02-05 09:08 UTC, deremenko commented on app.js
> +const mongoose = require("mongoose");
Corrected

2024-02-05 09:09 UTC, deremenko commented on scr/controllers/user-controller.js
> +const userService = require("../services/user-services.js");
Corrected

2024-02-05 09:16 UTC, deremenko commented on app.js
> +app.use(cors());
Corrected

2024-02-05 09:26 UTC, deremenko commented on scr/controllers/user-controller.js
> +      res.cookie('refreshToken', userData.refreshToken, {maxAge: 30 * 24 * 60 * 60, httpOnly: true});
Corrected

2024-02-05 09:27 UTC, deremenko commented on scr/middlewares/error-middleware.js
> +  console.error(err);
Corrected

2024-02-05 09:28 UTC, deremenko commented on scr/middlewares/user-validation.js
> +    .notEmpty(),
Corrected

2024-02-05 09:28 UTC, deremenko commented on scr/middlewares/user-validation.js
> +const { validatorResult } = require('./validation-result');
Corrected

2024-02-05 09:28 UTC, deremenko commented on scr/middlewares/user-validation.js
> +    .isString()
Corrected

2024-02-05 09:29 UTC, deremenko commented on scr/middlewares/user-validation.js
> +module.exports = {
Corrected

2024-02-05 09:31 UTC, deremenko commented on scr/router/index.js
> +const userController = require('./../controllers/user-controller.js');
Corrected

2024-02-05 09:35 UTC, deremenko commented on scr/middlewares/user-validation.js
> +    .matches(/^(?=.*[A-Za-z])(?=.*\d).+$/),
Тогда читаемость снизится

2024-02-05 09:41 UTC, deremenko commented on scr/services/token-services.js
> +    const accessToken = jwt.sign(payload, process.env.JWT_ACCESS_SECRET, {expiresIn: "30m"})
Corrected

2024-02-05 09:42 UTC, deremenko commented on scr/services/token-services.js
> +    if (tokenData) {
Corrected

2024-02-05 09:42 UTC, deremenko commented on scr/services/user-services.js
> +const tokenService = require("./token-services.js");
Corrected

2024-02-05 09:42 UTC, deremenko commented on scr/services/user-services.js
> +      throw ApiError.BadRequest(`Пользователь с логином ${login} уже существует`)
Corrected

2024-02-06 06:58 UTC, merged